### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [pnwairfire/air-monitor-plots#1]
Items as they come up:

-----
_TODO:_

_New in 2026_

**For Will -- Do this in a separate branch.**

_Items finished by 2026-06-10_
- [x] Add/update `CLAUDE.md` file and `.claude/prompts/` from `airfire-pdf-service` repo (06/05/2026)
- [x] Review code and make minor adjustments as you see fit (06/05/2026)
- [x] Create `CLAUDE_ARCHITECTURE.md` and `CLAUDE_UPDATES.md` files. (06/05/2026)

_New in 2025_

- [ ] `pm25ToColor()` (and other functions?) should handle character versions of numbers rather than just return gray. (7/22/2025)

----

_Items finished by 2025-07-08_

- [x] hourly barplot appears to show in client device local time, not sensor local time (8/13/2023)
